version: '3.1'

services:
  db:
    container_name: wp-mysql
    image: mysql:8.0
    volumes:
      - $PWD/data: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    networks:
      - wp_net

  wp:
    container_name: wp-web 
    image: wordpress
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db
    ports:
      - "9091:80"
    
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    
    networks:
      - wp_network

networks:
  wp_net: 
